- hosts: localhost
  become: true
  vars:
    # Generate a unique identifier for the Docker image and container
    docker_id: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"  # Timestamp as unique ID
    docker_container_name: "simple-calculator-{{ docker_id }}"
    docker_image_name: "simple-calculator-{{ docker_id }}"
    docker_port: "9292"  # Change this to any port you prefer
    docker_username: ""  # Change this to your username
    docker_password: ""  # Change this to your password

  tasks:
    - name: Check if Docker is already installed
      command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_installed.rc != 0

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: true

    - name: Build Docker Image
      command: docker build -t {{ docker_image_name }} .
      #args:
        #chdir: /path/to/docker/project  # Replace with your actual Docker project path

    - name: Run Docker Container
      command: docker run -d -p {{ docker_port }}:80 {{ docker_image_name }}

    - name: Log in to Docker Hub
      command: docker login -u "{{ docker_username }}" -p "{{ docker_password }}"
      no_log: true

    - name: Tag Docker image for Docker Hub
      command: docker tag {{ docker_image_name }} "{{ docker_username }}/{{ docker_image_name }}:latest"

    - name: Push Docker image to Docker Hub
      command: docker push "{{ docker_username }}/{{ docker_image_name }}:latest"
