- hosts: localhost
  become: true
  vars:
    # Generate a unique identifier for the Docker Build ID
    docker_id: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"  # Timestamp as unique ID

  tasks:
    - name: Load .env file
      shell: |
        set -a
        source /path/to/.env  # Replace with the path to your .env file
        set +a
      register: env_loaded

    - name: Check if Docker is already installed
      command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_installed.rc != 0

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: true

    - name: Build Docker Image
      command: docker build -t {{ lookup('env', 'docker_image_name') }}-{{ docker_id }} .
      #args:
        #chdir: /path/to/docker/project  # Replace with your actual Docker project path

    - name: Run Docker Container
      command: docker run -d -p {{ lookup('env', 'docker_port') }}:80 {{ lookup('env', 'docker_image_name') }}-{{ docker_id }}

    - name: Log in to Docker Hub
      command: docker login -u "{{ lookup('env', 'dockerhub_username') }}" -p "{{ lookup('env', 'dockerhub_password') }}"
      no_log: true

    - name: Tag Docker image for Docker Hub
      command: docker tag {{ lookup('env', 'docker_image_name') }}-{{ docker_id }} "{{ lookup('env', 'dockerhub_username') }}/{{ lookup('env', 'docker_image_name') }}-{{ docker_id }}:latest"

    - name: Push Docker image to Docker Hub
      command: docker push "{{ lookup('env', 'dockerhub_username') }}/{{ lookup('env', 'docker_image_name') }}-{{ docker_id }}:latest"
