- hosts: localhost
  become: true
  tasks:
    - name: Check if Docker is already installed
      command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_installed.rc != 0

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: true

    - name: Build Docker Image
      command: docker build -t simple-calculator-ansible .

    - name: Run Docker Container
      command: docker run -d -p 9292:80 simple-calculator-ansible
