apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-calculator-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-calculator
  template:
    metadata:
      labels:
        app: simple-calculator
    spec:
      containers:
        - name: simple-calculator
          image: simple-calculator
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-calculator-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: simple-calculator